In [14]:
import numpy as np
import pandas as pds
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [15]:
from alpha_vantage.timeseries import TimeSeries

# api_key = 'YOUR_ALPHA_VANTAGE_API_KEY'
api_key = 'SSW9AMG17A9Y5BBA'

In [16]:
ts = TimeSeries(key=api_key, output_format='pandas')

In [17]:
# NOTE: the free Alpha Vantage tier no longer covers what this cell used:
#   - get_daily_adjusted(...)            -> premium endpoint entirely
#   - get_daily(..., outputsize='full')  -> 'full' is a premium parameter too
# Free options that still work (verified 2026-09):
#   - get_daily('AMZN', outputsize='compact') -> last 100 trading days
#   - get_monthly('AMZN')                     -> full history since 1999, monthly bars
# amzn, _ = ts.get_monthly('AMZN')  # uncomment for full history, monthly bars

amzn, _ = ts.get_daily(symbol='AMZN', outputsize='compact')  # last ~100 trading days
amzn

            1. open  2. high   3. low  4. close    5. volume
date
2026-09-16   248.10   249.26  244.300    245.96   33488488.0
2026-09-15   252.24   253.27  247.220    248.42   36275442.0
2026-09-14   253.15   255.95  250.740    253.54   34352766.0
2026-09-11   254.09   257.59  253.140    256.78   26724121.0
2026-09-10   250.11   253.15  249.580    251.89   25484814.0
...             ...      ...      ...       ...          ...
2026-04-30   273.17   273.88  256.160    265.06  100974867.0
2026-04-29   257.99   265.91  257.700    263.04   72367910.0
2026-04-28   258.39   261.03  256.630    259.70   42204447.0
2026-04-27   263.46   264.15  260.340    261.12   44906840.0
2026-04-24   259.98   264.50  257.685    263.99   53777353.0

[100 rows x 5 columns]

In [18]:
amzn.columns = ['OPEN AMZN', 'HIGH AMZN', 'LOW AMZN', 'CLOSE AMZN', 'VOLUME AMZN']
amzn

            OPEN AMZN  HIGH AMZN  LOW AMZN  CLOSE AMZN  VOLUME AMZN
date
2026-09-16     248.10     249.26   244.300      245.96   33488488.0
2026-09-15     252.24     253.27   247.220      248.42   36275442.0
2026-09-14     253.15     255.95   250.740      253.54   34352766.0
2026-09-11     254.09     257.59   253.140      256.78   26724121.0
2026-09-10     250.11     253.15   249.580      251.89   25484814.0
...               ...        ...       ...         ...          ...
2026-04-30     273.17     273.88   256.160      265.06  100974867.0
2026-04-29     257.99     265.91   257.700      263.04   72367910.0
2026-04-28     258.39     261.03   256.630      259.70   42204447.0
2026-04-27     263.46     264.15   260.340      261.12   44906840.0
2026-04-24     259.98     264.50   257.685      263.99   53777353.0

[100 rows x 5 columns]

In [19]:
amzn = amzn.sort_index(axis=0, ascending=True)
pctamzn = amzn.pct_change().dropna()
pctamzn

            OPEN AMZN  HIGH AMZN  LOW AMZN  CLOSE AMZN  VOLUME AMZN
date
2026-04-27   0.013386  -0.001323  0.010303   -0.010872    -0.164949
2026-04-28  -0.019244  -0.011811 -0.014251   -0.005438    -0.060178
2026-04-29  -0.001548   0.018695  0.004169    0.012861     0.714699
2026-04-30   0.058839   0.029973 -0.005976    0.007679     0.395299
2026-05-01  -0.027785  -0.002063  0.025687    0.012073    -0.496655
...               ...        ...       ...         ...          ...
2026-09-10  -0.011892  -0.006047 -0.004269   -0.002021    -0.229029
2026-09-11   0.015913   0.017539  0.014264    0.019413     0.048629
2026-09-14  -0.003699  -0.006367 -0.009481   -0.012618     0.285459
2026-09-15  -0.003595  -0.010471 -0.014038   -0.020194     0.055969
2026-09-16  -0.016413  -0.015833 -0.011811   -0.009903    -0.076828

[99 rows x 5 columns]

Set of data

In [ ]:
a = 3900
l=len(amzn)

X_train = amzn.iloc[0:a-1, 0:].values
y_train = amzn[["CLOSE AMZN"]].iloc[1:a:].values

X_visu = amzn.iloc[a:]